import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import Image from "next/image"
import { myimages } from "../../public/assets_export"

export default function Home() {
  return (
    <>
      <Head>
        <title>Almanac</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      <div className={styles.arrange}>

        <div className={styles.nav}>
          <Image src={myimages.journalCover} width={200}/>
          <Link href="/menu_page" className={styles.navlink}>Try Journal</Link>
        </div>

        <div className={styles.intro}>
          <h1 className={styles.introtitle}>
          Unlock your thoughts and unleash your creativity with our <Link href="/menu_page">Journal</Link> app.
          </h1>
        </div>

      </div>

    
    </>
  );
}
