// import{Children, useEffect, useState} from "react"
import { useEditor, EditorContent} from "@tiptap/react"
import StarterKit from "@tiptap/starter-kit"
// import styless from "./Tiptap.module.css"
import { Node, Selection } from "@tiptap/core"
import Placeholder from "@tiptap/extension-placeholder"
import Heading from "@tiptap/extension-heading"
import { EditorState } from "@tiptap/pm/state"
import Document from "@tiptap/extension-document"
// import { images } from "../../public/assets_export"
import { Color } from "@tiptap/extension-color"
import ListItem from "@tiptap/extension-list-item"
import TextStyle from "@tiptap/extension-text-style"
// import Image from "next/image"
// import {BubbleMenu} from "@tiptap/react"
import Highlight from "@tiptap/extension-highlight"
import Typography from "@tiptap/extension-typography"
import TextAlign from "@tiptap/extension-text-align"
import TaskList from "@tiptap/extension-task-list"
import TaskItem from "@tiptap/extension-task-item"
import Text from "@tiptap/extension-text"
// import Drawer from "react-modern-drawer"
// import 'react-modern-drawer/dist/index.css'
// import dynamic from "next/dynamic"
// import EmojiPicker, {EmojiStyle, EmojiClickData, Emoji} from "emoji-picker-react"
// import { yellow } from "@mui/material/colors"
// import headbuttons from "@/utils/menubarClass"
import Paragraph from "@tiptap/starter-kit"
import Bold from "@tiptap/starter-kit"


export {useEditor, EditorContent, StarterKit, Placeholder,Node, Selection, Color, EditorState, Heading, Document, ListItem, TextStyle, Highlight, Typography, TextAlign, TaskList, TaskItem, Text, Paragraph, Bold}