import{useEffect, useState} from "react"
import { useEditor, EditorContent} from "@tiptap/react"
import StarterKit from "@tiptap/starter-kit"
import styless from "./Tiptap.module.css"
import { Node, Selection } from "@tiptap/core"
import Placeholder from "@tiptap/extension-placeholder"
import Heading from "@tiptap/extension-heading"
import { EditorState } from "@tiptap/pm/state"
import Document from "@tiptap/extension-document"
import { images } from "../../public/assets_export"
import { Color } from "@tiptap/extension-color"
import ListItem from "@tiptap/extension-list-item"
import TextStyle from "@tiptap/extension-text-style"
import Image from "next/image"
import {BubbleMenu, FloatingMenu} from "@tiptap/react"
import Highlight from "@tiptap/extension-highlight"
import Typography from "@tiptap/extension-typography"
import TextAlign from "@tiptap/extension-text-align"
import TaskList from "@tiptap/extension-task-list"
import TaskItem from "@tiptap/extension-task-item"
import Text from "@tiptap/extension-text"

export {useEffect, useState, useEditor, EditorContent, StarterKit}